package com.apt.core.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Alert — a risk-scored security incident generated by the detection engine.
 *
 * Stored in PostgreSQL (alerts table) because:
 *  - Alerts have structured, relational data (entity → alert → response action)
 *  - We need complex queries (filter by score, join with entity profiles)
 *  - Audit trails require ACID transactions
 *
 * The shapDrivers field is JSONB — PostgreSQL stores it as structured JSON
 * but we can query specific keys. This lets us store a flexible list of
 * "why was this flagged?" explanations without a separate table.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "alerts", indexes = {
    @Index(name = "idx_alerts_entity_id",  columnList = "entity_id"),
    @Index(name = "idx_alerts_risk_score", columnList = "risk_score"),
    @Index(name = "idx_alerts_created_at", columnList = "created_at"),
    @Index(name = "idx_alerts_status",     columnList = "status")
})
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "entity_id", nullable = false)
    private String entityId;              // The user or device that triggered this alert

    @Column(name = "risk_score", nullable = false)
    private int riskScore;                // 0–100 unified risk score

    @Column(name = "isolation_forest_score")
    private double isolationForestScore;  // Raw IF anomaly score

    @Column(name = "autoencoder_error")
    private double autoencoderError;      // Raw reconstruction error

    @Column(name = "peer_deviation")
    private double peerDeviation;         // How far from peer-group norm

    @Column(name = "mitre_technique_id")
    private String mitreTechniqueId;      // e.g. "T1078"

    @Column(name = "mitre_technique_name")
    private String mitreTechniqueName;    // e.g. "Valid Accounts"

    @Column(name = "mitre_tactic")
    private String mitreTactic;           // e.g. "Defense Evasion"

    /**
     * SHAP explainability drivers — stored as JSONB in PostgreSQL.
     * Example: [{"feature": "login_hour", "contribution": 42.5,
     *             "description": "Login at 3:14 AM (+42 pts)"}]
     * This tells the SOC analyst exactly WHY the alert was generated.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "shap_drivers", columnDefinition = "jsonb")
    private List<ShapDriver> shapDrivers;

    @Column(name = "raw_event_id")
    private String rawEventId;            // Reference to MongoDB NetworkEvent

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private AlertStatus status = AlertStatus.OPEN;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "resolved_at")
    private Instant resolvedAt;

    @Column(name = "resolved_by")
    private String resolvedBy;

    /** Possible lifecycle states for an alert */
    public enum AlertStatus {
        OPEN,           // Newly generated, awaiting triage
        INVESTIGATING,  // SOC analyst is looking at it
        RESOLVED,       // Determined to be a true positive, handled
        FALSE_POSITIVE, // Determined to be benign
        AUTO_MITIGATED  // Automated response already taken
    }

    /** A single SHAP explanation: which feature drove the score and by how much */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ShapDriver {
        private String feature;          // e.g. "login_hour"
        private double contribution;     // e.g. 42.5 (points added to risk score)
        private String description;      // Human-readable: "Login at 3:14 AM"
        private double actualValue;      // The anomalous value observed
        private double baselineValue;    // What we expected (μ for this feature)
    }
}
